## Try and Accept:
The `try` block lets you test a block of code for errors.
The `except` block lets you handle the error.
The `finally` block lets you execute code, regardless of the result of the try/except blocks.

#### Syntax:
```py
try:
	print(x)
except:
	print("An exception occurred")
	
# The `try` block will generate an exception, because x is not defined
```



[Python Try Except](https://www.w3schools.com/python/python_try_except.asp)